### ISSUE TITLE
Bert example doesn't work

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [wellcometrust/WellcomeML#135]
I've been trying to run the bert vectoriser example from https://github.com/wellcometrust/WellcomeML/blob/master/examples/bert_embeddings.py but I run into the following error.

```
        build/virtualenv/bin/python src/create_bert_embedding.py
2020-09-14 19:03:44.719208: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-14 19:03:46.446415: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-14 19:03:46.630520: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-09-14 19:03:46.630551: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (xps15): /proc/driver/nvidia/version does not exist
2020-09-14 19:03:46.631071: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-14 19:03:46.656781: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2899885000 Hz
2020-09-14 19:03:46.658066: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f30e420da0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-14 19:03:46.658088: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-14 19:03:46.671782: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-09-14 19:03:46.699506: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-09-14 19:03:46 wellcomeml.logger INFO: Using bert-base-uncased embedding
Traceback (most recent call last):
  File "src/create_bert_embedding.py", line 16, in <module>
    X_transformed = vectorizer.fit_transform(X)
  File "/home/matthew/Documents/wellcome/grant-embedding/build/virtualenv/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/matthew/Documents/wellcome/grant-embedding/build/virtualenv/lib/python3.7/site-packages/wellcomeml/ml/bert_vectorizer.py", line 89, in fit
    self.model = BertModel.from_pretrained(model_name, output_hidden_states=True)
  File "/home/matthew/Documents/wellcome/grant-embedding/build/virtualenv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 345, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/home/matthew/Documents/wellcome/grant-embedding/build/virtualenv/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/matthew/Documents/wellcome/grant-embedding/build/virtualenv/lib/python3.7/site-packages/torch/serialization.py", line 772, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 5274485 more bytes. The file might be corrupted.
ERROR: failed to reproduce 'dvc.yaml': failed to run: build/virtualenv/bin/python src/create_bert_embedding.py, exited with 1

```

**Comment by ivyleavedtoadflax** [comment]
Seems to be a resolution here: https://github.com/huggingface/transformers/issues/1491

**Comment by ivyleavedtoadflax** [comment]
:point_up: this didn't work for me :(

**Comment by ivyleavedtoadflax** [comment]
Also deleted my virtualenv and rebuilt, still no dice :game_die: :cry:

**Comment by ivyleavedtoadflax** [comment]
Solved by deleting `~/.cache/torch` :fire: :fire_engine:
